baseurl         = "https://yukara-ikemiya.github.io/arayuru-genjitu-blog/"
theme           = "casper-two"
languageCode    = "ja-jp"
hasCJKLanguage 	= true
disqusShortname = ""
paginate        = 6
# SectionPagesMenu = "main"
RelativeURLs    = true
CanonifyURLs	  = true
publishDir = "docs"


[params]
  title       = "あらゆる現実のはなし"
  subtitle    = "たまに役に立つ雑記帳"
  copyright   = "© 2019--2022"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = "日々の思いつきをまとめた日記・雑記帳"
  googleAnalytics = "G-X43C8XPK6Q"
  customCSS = ["css/jp-font.css"]
  RSSLink = ""

  twitterName = "yukara_ikemiya"
  fbName = ""
  githubName = "yukara-ikemiya"
  linkedinName = "yukara-ikemiya-16a6b85a"
  mediumName = ""

  logo = ""
  orgName = "Yukara Ikemiya"
  orgWebsite = ""
  orgDescription = "audio software engineer"

  showSupport = true

  author = "YUKARA IKEMIYA"
  authorAvatar = "img/yukara_profile.jpg"
  authorLocation = "Kanagawa, Japan"
  authorWebsite = "https://yukara-ikemiya.github.io/arayuru-genjitu-blog/"
  authorDescription = "audio software engineer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:filename/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99


[markup.goldmark.renderer]
  unsafe = true

